config/routes.rb
Rails.application.routes.draw do

  resources :user_details
  resources :medical_events
  resources :preferences

  get 'horizontal' => 'medical_events#horizontal', as: :horizontal

  get 'appointments' => 'landings#appointments', as: :appointments
  get 'prescriptions' => 'landings#prescriptions', as: :prescriptions
  get 'conditions' => 'landings#conditions', as: :conditions

  devise_for :users, controllers: {registrations: "users/registrations", sessions: "users/sessions", passwords: "users/passwords"}, skip: [:sessions, :registrations]

  root 'landings#index'

  
  devise_scope :user do
    get    "login"   => "users/sessions#new",         as: :new_user_session
    post   "login"   => "users/sessions#create",      as: :user_session
    delete "signout" => "users/sessions#destroy",     as: :destroy_user_session
    
    get    "signup"  => "users/registrations#new",    as: :new_user_registration
    post   "signup"  => "users/registrations#create", as: :user_registration
    put    "signup"  => "users/registrations#update", as: :update_user_registration
    get    "account" => "users/registrations#edit",   as: :edit_user_registration
  end

end

app/models/preference.rb
class Preference < ActiveRecord::Base
	belongs_to :user
	validates_presence_of :care_data_privacty_setting

	CARE_DATA_SETTING_VALUES = { 10 => "Allow my personal health data to be used for secondary uses.", 
		20 => "In fully identifiable form - including my name, date of birth, address and other personal information.", 
		30 => "In pseudonymised form by researchers for the public good only.", 
		40 => "In pseudonymised form by anyone, including researchers and private companies.", 
		50 => "In anonymised form, for public health and statistics.", 
		60 => "Allow me to decide for each individual secondary use request.", 
		70 => "Do not allow my personal health data to be used for secondary uses." }
end

app/controllers/preferences_controller.rb
class PreferencesController < ApplicationController
  before_filter :authenticate_user!
  before_action :set_preference, only: [:show, :edit, :update, :destroy]
  
  # GET /preferences
  # GET /preferences.json
  def index
    if current_user.preference
      @preference = current_user.preference
      render :edit      
    else #First use, so let's redirect to new
      redirect_to new_preference_path
    end
  end

  # GET /preferences/1
  # GET /preferences/1.json
  # def show
  # end

  # GET /preferences/new
  def new
    @preference = Preference.new
  end

  # GET /preferences/1/edit
  def edit
  end

  # POST /preferences
  # POST /preferences.json
  def create
    @preference = Preference.new(preference_params)
    @preference.user = current_user

    respond_to do |format|
      if @preference.save
        format.html { redirect_to @preference, notice: 'Preference was successfully created.' }
        format.json { render :show, status: :created, location: @preference }
      else
        format.html { render :new }
        format.json { render json: @preference.errors, status: :unprocessable_entity }
      end
    end

  end

  # PATCH/PUT /preferences/1
  # PATCH/PUT /preferences/1.json
  def update
    respond_to do |format|
      if @preference.update(preference_params)
        format.html { redirect_to @preference, notice: 'Preference was successfully updated.' }
        format.json { render :show, status: :ok, location: @preference }
      else
        format.html { render :edit }
        format.json { render json: @preference.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /preferences/1
  # DELETE /preferences/1.json
  def destroy
    #TODO-IM: I'm assuming that it should not be possible for a user to remove their preference altogether.
    #@preference.destroy

    respond_to do |format|
      format.html { redirect_to preferences_url, notice: 'Preference was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.

    def set_preference
      # We need to scope this to the current user's preference
      @preference = current_user.preference
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def preference_params
      params.require(:preference).permit(:care_data_privacty_setting)
    end
end

app/helpers/preferences_helper.rb
module PreferencesHelper
end

app/views/preferences/_form.html.erb
<%= form_for @preference, :html => { :class => 'form-horizontal form-model' } do |f| %>
  
  <div class="form-group">
    <div class="col-md-10">        

    <ul>
      <% Preference::CARE_DATA_SETTING_VALUES.each do |index, value| %>
        <li>
          <%= f.radio_button( :care_data_privacty_setting, index ) %>    
          <%= f.label( "care_data_privacty_setting", value ) %>
        </li>
      <% end %>
    </ul>

    </div>
  </div>

  <div class="form-group">
    <div class='col-md-offset-2 col-md-10'>
      <%= f.submit nil, :class => 'btn btn-primary' %>      
    </div>
  </div>

<% end %>

app/views/preferences/edit.html.erb
<div class="page-header">
  <h1> Edit Data.Care Preference </h1>
</div>

<%= render :partial => 'form' %>

app/views/preferences/index.html.erb
<%- model_class = Preference -%>
<div class="page-header">
  <h1><%=t '.title', :default => Preference %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th>ID</th>
      <th><%= model_class.human_attribute_name(:care_data_privacty_setting) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @preferences.each do |preference| %>
      <tr>
        <td><%= preference.id %></td>
        <td><%= preference.care_data_privacty_setting %></td>
        <td><%=l preference.created_at, format: :long %></td>
        <td>
          <%= link_to preference_path(preference), :class => 'btn btn-xs', :title => "#{ t('.show', :default => t('helpers.links.show')) }" do %>
            <%= glyph 'info-sign' %>
            <%= glyph 'pencil' %>
          <%- end -%>
          <%= link_to preference_path(preference), :method => :delete, :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }, :class => 'btn btn-xs', :title => "#{ t('.destroy', :default => t('helpers.links.destroy')) }" do %>
            <%= glyph 'remove' %>
          <%- end -%>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_preference_path,
            :class => 'btn btn-primary' %>

app/views/preferences/new.html.erb
<%- model_class = Preference -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => Preference %></h1>
</div>
<%= render :partial => 'form' %>

app/views/preferences/show.html.erb
<%- model_class = Preference -%>
<div class="page-header">
  <h1><%=t '.title', :default => "Your Data.Care Preference" %></h1>
</div>

<p>
  Your care.data privacy setting: <%= Preference::CARE_DATA_SETTING_VALUES[current_user.preference.care_data_privacty_setting] %>
</p>

<div class="form-group">  
  <%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_preference_path(@preference), :class => 'btn btn-default' %>  
</div>