config/routes.rb
Rails.application.routes.draw do

  resources :user_details
  resources :medical_events
  resources :preferences

  get 'horizontal' => 'medical_events#horizontal', as: :horizontal

  get 'appointments' => 'landings#appointments', as: :appointments
  get 'prescriptions' => 'landings#prescriptions', as: :prescriptions
  get 'conditions' => 'landings#conditions', as: :conditions

  devise_for :users, controllers: {registrations: "users/registrations", sessions: "users/sessions", passwords: "users/passwords"}, skip: [:sessions, :registrations]

  root 'landings#index'

  
  devise_scope :user do
    get    "login"   => "users/sessions#new",         as: :new_user_session
    post   "login"   => "users/sessions#create",      as: :user_session
    delete "signout" => "users/sessions#destroy",     as: :destroy_user_session
    
    get    "signup"  => "users/registrations#new",    as: :new_user_registration
    post   "signup"  => "users/registrations#create", as: :user_registration
    put    "signup"  => "users/registrations#update", as: :update_user_registration
    get    "account" => "users/registrations#edit",   as: :edit_user_registration
  end

end

app/models/medical_event.rb
class MedicalEvent < ActiveRecord::Base
  belongs_to :user
end

app/controllers/medical_events_controller.rb
class MedicalEventsController < ApplicationController

  before_filter :require_user_signed_in

  before_action :set_medical_event, only: [:show, :edit, :update, :destroy]

  # GET /medical_events
  # GET /medical_events.json
  def index
    @medical_events = current_user.medical_events.order(occurred_at: :desc)
  end

  def horizontal
    # An experiment to see how the time would look in a 
    @medical_events = current_user.medical_events.order(id: :asc)

    render :layout => 'main'
  end

  # GET /medical_events/1
  # GET /medical_events/1.json
  def show
  end

  # GET /medical_events/new
  def new
    @medical_event = MedicalEvent.new
  end

  # GET /medical_events/1/edit
  def edit
  end

  # POST /medical_events
  # POST /medical_events.json
  def create
    @medical_event = MedicalEvent.new(medical_event_params)
    @medical_event.user = current_user

    respond_to do |format|
      if @medical_event.save
        format.html { redirect_to @medical_event, notice: 'Medical event was successfully created.' }
        format.json { render :show, status: :created, location: @medical_event }
      else
        format.html { render :new }
        format.json { render json: @medical_event.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /medical_events/1
  # PATCH/PUT /medical_events/1.json
  def update
    respond_to do |format|
      if @medical_event.update(medical_event_params)
        format.html { redirect_to @medical_event, notice: 'Medical event was successfully updated.' }
        format.json { render :show, status: :ok, location: @medical_event }
      else
        format.html { render :edit }
        format.json { render json: @medical_event.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /medical_events/1
  # DELETE /medical_events/1.json
  def destroy
    @medical_event.destroy
    respond_to do |format|
      format.html { redirect_to medical_events_url, notice: 'Medical event was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.

    def set_medical_event      
      # We need to scope this to the current_user so that other users cannot access their events.
      begin
        @medical_event = current_user.medical_events.find(params[:id])
      rescue ActiveRecord::RecordNotFound => not_users_record_exception
        Rails.logger.error "Current User: #{current_user.email} is attempting to access someone elses record - MedicalEvent: #{params[:id]}"
        redirect_to :root, notice: 'You do not have permission to access that.'
      end
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def medical_event_params
      params.require(:medical_event).permit(:summary, :description, :occurred_at)
    end
end

app/helpers/medical_events_helper.rb
module MedicalEventsHelper
end

app/views/medical_events/_form.html.erb
<%= form_for @medical_event, :html => { :class => 'form-horizontal form-model' } do |f| %>
  <div class="form-group">
    <%= f.label :summary, :class => 'control-label col-md-2' %>
    <div class="col-md-10">
      <%= f.text_field :summary, :class => 'text-field form-control' %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :description, :class => 'control-label col-md-2' %>
    <div class="col-md-10">
      <%= f.text_area :description, :class => 'text-field form-control' %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :occurred_at, :class => 'control-label col-md-2' %>
    <div class="col-md-10">
      <%= f.datetime_select :occurred_at, :class => 'text-field form-control' %>
    </div>
  </div>

  <div class="form-group">
    <div class='col-md-offset-2 col-md-10'>
      <%= f.submit nil, :class => 'btn btn-primary' %>
      <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                  medical_events_path, :class => 'btn btn-default' %>
    </div>
  </div>
<% end %>

app/views/medical_events/edit.html.erb
<%- model_class = MedicalEvent -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => MedicalEvent %></h1>
</div>
<%= render :partial => 'form' %>

app/views/medical_events/horizontal.html.erb
<h1>Horizontal Timeline</h1>

<p>
 	Here we will trial out the horizontal timeline.
</p>

<div id="visualization"></div>

<script type="text/javascript">
  // DOM element where the Timeline will be attached
  var container = document.getElementById('visualization');

  // Create a DataSet (allows two way data-binding)
  var data = new vis.DataSet([
    {id: 1, content: 'item 1', start: '2014-12-12'},
    {id: 2, content: 'item 2', start: '2014-12-14'},
    <% @medical_events.each do |medical_event| %>
        { id: <%= medical_event.id.to_s %>, content: '<%= medical_event.summary %>', start: '<%= medical_event.occurred_at.strftime("%F") %>' },
    <% end %>
    {id: 60, content: 'item 6', start: '2014-12-29'}
  ]);

    // Configuration for the Timeline
  var options = {};

  // Create a Timeline
  var timeline = new vis.Timeline(container, data, options);
</script>

app/views/medical_events/index.html.erb
<%- model_class = MedicalEvent -%>
<div class="page-header">
  <h1><%=t '.title', :default => "Your Medical Event Timeline" %></h1>
</div>

<%= link_to t('.new', :default => t("new_medical_event")),
            new_medical_event_path,
            :class => 'btn btn-primary' %>

<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:occurred_at) %></th>
      <th><%= model_class.human_attribute_name(:summary) %></th>
      <th><%= model_class.human_attribute_name(:description) %></th>      
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @medical_events.each do |medical_event| %>
      <tr>
        <td><%=l medical_event.occurred_at, format: :long %></td>
        <td><%= medical_event.summary %></td>
        <td><%= medical_event.description %></td>        
        <td>
          <%= link_to medical_event_path(medical_event), :class => 'btn btn-xs', :title => "#{ t('.show', :default => t('helpers.links.show')) }" do %>
            <%= glyph 'info-sign' %>
            <%= glyph 'pencil' %>
          <%- end -%>
          <%= link_to medical_event_path(medical_event), :method => :delete, :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }, :class => 'btn btn-xs', :title => "#{ t('.destroy', :default => t('helpers.links.destroy')) }" do %>
            <%= glyph 'remove' %>
          <%- end -%>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("new_medical_event")),
            new_medical_event_path,
            :class => 'btn btn-primary' %>

app/views/medical_events/new.html.erb
<%- model_class = MedicalEvent -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => MedicalEvent %></h1>
</div>
<%= render :partial => 'form' %>

app/views/medical_events/show.html.erb
<%- model_class = MedicalEvent -%>
<div class="page-header">
  <h1><%=t '.title', :default => MedicalEvent %></h1>
</div>

<div class="fieldset">
  <dl>
      <dt class="label label-default"><%= model_class.human_attribute_name(:occurred_at) %></dt>
      <dd><pre class="prettyprint"><%= @medical_event.occurred_at %></pre></dd>

      <dt class="label label-default"><%= model_class.human_attribute_name(:summary) %></dt>
      <dd><pre class="prettyprint"><%= @medical_event.summary %></pre></dd>

      <dt class="label label-default"><%= model_class.human_attribute_name(:description) %></dt>
      <dd><pre class="prettyprint"><%= @medical_event.description %></pre></dd>

      <dt class="label label-default"><%= model_class.human_attribute_name(:id) %></dt>
      <dd><pre class="prettyprint"><%= @medical_event.id %></pre></dd>

      <dt class="label label-default"><%= model_class.human_attribute_name(:created_at) %></dt>
      <dd><pre class="prettyprint"><%= @medical_event.occurred_at %></pre></dd>      
  </dl>
</div>

<div class="form-group">
  <%= link_to t('.back', :default => t("helpers.links.show_timeline")),
              medical_events_path, :class => 'btn btn-default'  %>
  <%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_medical_event_path(@medical_event), :class => 'btn btn-default' %>
  <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              medical_event_path(@medical_event),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>
</div>