config/routes.rb
Rails.application.routes.draw do

  resources :user_details
  resources :medical_events
  resources :preferences

  get 'horizontal' => 'medical_events#horizontal', as: :horizontal

  get 'appointments' => 'landings#appointments', as: :appointments
  get 'prescriptions' => 'landings#prescriptions', as: :prescriptions
  get 'conditions' => 'landings#conditions', as: :conditions

  devise_for :users, controllers: {registrations: "users/registrations", sessions: "users/sessions", passwords: "users/passwords"}, skip: [:sessions, :registrations]

  root 'landings#index'

  
  devise_scope :user do
    get    "login"   => "users/sessions#new",         as: :new_user_session
    post   "login"   => "users/sessions#create",      as: :user_session
    delete "signout" => "users/sessions#destroy",     as: :destroy_user_session
    
    get    "signup"  => "users/registrations#new",    as: :new_user_registration
    post   "signup"  => "users/registrations#create", as: :user_registration
    put    "signup"  => "users/registrations#update", as: :update_user_registration
    get    "account" => "users/registrations#edit",   as: :edit_user_registration
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  private
  
  #-> Prelang (user_login:devise)
  def require_user_signed_in
    unless user_signed_in?

      # If the user came from a page, we can send them back.  Otherwise, send
      # them to the root path.
      if request.env['HTTP_REFERER']
        fallback_redirect = :back
      elsif defined?(root_path)
        fallback_redirect = root_path
      else
        fallback_redirect = "/"
      end

      redirect_to fallback_redirect, flash: {error: "You must be signed in to view this page."}
    end
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/application/_left_column.html.erb
app/views/application/_right_column.html.erb
<% # a 2 cell width navigation area included from application.html.erb %>

<ul class="list-unstyled">
  
	<li><%= link_to t('.new', :default => t("appointments")),
	            appointments_path,
	            :class => 'btn btn-primary' %></li>


	<li><%= link_to t('.new', :default => t("prescriptions")),
	            prescriptions_path,
	            :class => 'btn btn-primary' %></li>

	<li><%= link_to t('.new', :default => t("conditions")),
	            conditions_path,
	            :class => 'btn btn-primary' %></li>
</ul>          

app/views/application/_navbar.html.erb
<nav class="navbar navbar-default" role="navigation">
  <!-- Brand and toggle get grouped for better mobile display -->
  <div class="navbar-header">
    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#navbar-collapse-1">
      <span class="sr-only">Toggle navigation</span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
    </button>
    <%= link_to "Fredbook", defined?(root_path) ? root_path : "#", class: "navbar-brand" %>
  </div>

  <!-- Collect the nav links, forms, and other content for toggling -->
  <div class="collapse navbar-collapse" id="navbar-collapse-1">
    <ul class="nav navbar-nav">
    </ul>
    <ul class="nav navbar-nav navbar-right">
      <% if defined?(Devise) %>
        <% if user_signed_in? %>
          <li><%= link_to "Timeline", root_path %></li>
          <li class="divider"></li>          
          <li><%= link_to "Data.Care Preferences", preferences_path %></li>
          <li class="divider"></li>          
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">Account <b class="caret"></b></a>
            <ul class="dropdown-menu">
              <li><%= link_to "User Details", user_details_path %></li>
              <li class="divider"></li>
              <li><%= link_to "Edit Account", edit_user_registration_path %></li>
              <li class="divider"></li>
              <li><%= link_to "Sign Out", destroy_user_session_path, method: :delete %></li>
            </ul>
          </li>
        <% else %>
          <li><%= link_to "Login", new_user_session_path %></li>
          <li><%= link_to "Sign Up", new_user_registration_path %></li>
        <% end %>
      <% end %>
    </ul>
  </div><!-- /.navbar-collapse -->
</nav>

app/views/application/_right_column.html.erb
	app/views/application/_right_column.html.erb
	<% # a 2 cell width navigation area included from application.html.erb %>

	<div id="latest_offer">
		<h3>Did you know you can get a flu vaccine?</h3>
		<a href="http://www.nhs.uk/Conditions/vaccinations/Pages/who-should-have-flu-vaccine.aspx">Find out more</a>
	</div>