config/routes.rb
Rails.application.routes.draw do

  resources :user_details
  resources :medical_events
  resources :preferences

  get 'horizontal' => 'medical_events#horizontal', as: :horizontal

  get 'appointments' => 'landings#appointments', as: :appointments
  get 'prescriptions' => 'landings#prescriptions', as: :prescriptions
  get 'conditions' => 'landings#conditions', as: :conditions

  devise_for :users, controllers: {registrations: "users/registrations", sessions: "users/sessions", passwords: "users/passwords"}, skip: [:sessions, :registrations]

  root 'landings#index'

  
  devise_scope :user do
    get    "login"   => "users/sessions#new",         as: :new_user_session
    post   "login"   => "users/sessions#create",      as: :user_session
    delete "signout" => "users/sessions#destroy",     as: :destroy_user_session
    
    get    "signup"  => "users/registrations#new",    as: :new_user_registration
    post   "signup"  => "users/registrations#create", as: :user_registration
    put    "signup"  => "users/registrations#update", as: :update_user_registration
    get    "account" => "users/registrations#edit",   as: :edit_user_registration
  end

end

app/models/user_detail.rb
class UserDetail < ActiveRecord::Base
	belongs_to :user
end

app/controllers/user_details_controller.rb
class UserDetailsController < ApplicationController
  before_filter :authenticate_user!
  before_action :set_user_detail, only: [:show, :edit, :update, :destroy]

  respond_to :html

  def index

    if current_user.user_detail
      @user_detail = current_user.user_detail
      render :edit      
    else #First use, so let's redirect to new
      redirect_to new_user_detail_path
    end

  end

  def show
    respond_with(@user_detail)
  end

  def new
    @user_detail = UserDetail.new
    respond_with(@user_detail)
  end

  def edit
    if current_user.user_detail.nil?      
      redirect_to new_user_detail_path
    end
  end

  def create
    @user_detail = UserDetail.new(user_detail_params)
    @user_detail.user = current_user
    @user_detail.save

    respond_with(@user_detail)
  end

  def update
    @user_detail.update(user_detail_params)

    respond_with(@user_detail)
  end

  def destroy
    # This should blank all of the User Detail    
  end

  private
    def set_user_detail
      @user_detail = current_user.user_detail 
    end

    def user_detail_params
      params.require(:user_detail).permit(:first_name, :last_name, :needs, :carers, :cares_for)
    end
end

app/helpers/user_details_helper.rb
module UserDetailsHelper
end

app/views/user_details/_form.html.erb
<%= form_for(@user_detail) do |f| %>

  <% if @user_detail.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user_detail.errors.count, "error") %> prohibited this user detail from being saved:</h2>
      <ul>
      <% @user_detail.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :first_name %><br>
    <%= f.text_field :first_name %>
  </div>
  <div class="field">
    <%= f.label :last_name %><br>
    <%= f.text_field :last_name %>
  </div>
  <div class="field">
    <%= f.label :needs %><br>
    <%= f.text_field :needs %>
  </div>
  <div class="field">
    <%= f.label :carers %><br>
    <%= f.text_field :carers %>
  </div>
  <div class="field">
    <%= f.label :cares_for %><br>
    <%= f.text_area :cares_for %>
  </div>
  
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/user_details/edit.html.erb
<h1>Editing Your User Details</h1>

<%= render 'form' %>

app/views/user_details/index.html.erb
<h1>Listing user_details</h1>

<table>
  <thead>
    <tr>
      <th>First name</th>
      <th>Last name</th>
      <th>Needs</th>
      <th>Carers</th>
      <th>Cares for</th>
      <th>User</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @user_details.each do |user_detail| %>
      <tr>
        <td><%= user_detail.first_name %></td>
        <td><%= user_detail.last_name %></td>
        <td><%= user_detail.needs %></td>
        <td><%= user_detail.carers %></td>
        <td><%= user_detail.cares_for %></td>
        <td><%= user_detail.user_id %></td>
        <td><%= link_to 'Show', user_detail %></td>
        <td><%= link_to 'Edit', edit_user_detail_path(user_detail) %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User detail', new_user_detail_path %>

app/views/user_details/new.html.erb
<h1>New User Details</h1>

<%= render 'form' %>

app/views/user_details/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>First name:</strong>
  <%= @user_detail.first_name %>
</p>

<p>
  <strong>Last name:</strong>
  <%= @user_detail.last_name %>
</p>

<p>
  <strong>Needs:</strong>
  <%= @user_detail.needs %>
</p>

<p>
  <strong>Carers:</strong>
  <%= @user_detail.carers %>
</p>

<p>
  <strong>Cares for:</strong>
  <%= @user_detail.cares_for %>
</p>

<%= link_to 'Edit', edit_user_detail_path(@user_detail) %>